# Generated by Django 5.2.3 on 2025-06-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.EmailField(help_text='Gmail account email', max_length=254, unique=True)),
                ('last_history_id', models.CharField(help_text='Last processed history ID for incremental sync', max_length=255)),
                ('last_sync_at', models.DateTimeField(auto_now=True, help_text='When the last sync completed')),
            ],
            options={
                'ordering': ['-last_sync_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleMailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('account_email', models.EmailField(help_text='Gmail account email this message belongs to', max_length=254)),
                ('history_id', models.CharField(max_length=255)),
                ('thread_id', models.CharField(max_length=255)),
                ('snippet', models.TextField()),
                ('label_ids', models.JSONField()),
                ('raw', models.BinaryField()),
                ('internal_date', models.PositiveBigIntegerField()),
                ('size_estimate', models.PositiveIntegerField(blank=True, help_text='Estimated size in bytes', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-internal_date'],
                'indexes': [models.Index(fields=['account_email'], name='google_emai_account_938e9f_idx'), models.Index(fields=['thread_id'], name='google_emai_thread__9e8d07_idx'), models.Index(fields=['internal_date'], name='google_emai_interna_46396a_idx'), models.Index(fields=['is_read'], name='google_emai_is_read_cdb03a_idx'), models.Index(fields=['account_email', 'internal_date'], name='google_emai_account_e9fb91_idx')],
                'constraints': [models.UniqueConstraint(fields=('message_id', 'account_email'), name='unique_message_per_account')],
            },
        ),
    ]
