# Generated by Django 5.2.3 on 2025-06-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_email_indexer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedEmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Normalized (lowercase) email address', max_length=254, unique=True)),
                ('display_name', models.CharField(blank=True, help_text='Most common display name for this email', max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Number of messages this email appears in')),
            ],
            options={
                'ordering': ['email'],
                'indexes': [models.Index(fields=['email'], name='google_emai_email_49a3d5_idx'), models.Index(fields=['message_count'], name='google_emai_message_a1f7d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageEmailAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('from', 'From'), ('to', 'To'), ('cc', 'CC'), ('bcc', 'BCC'), ('reply_to', 'Reply-To')], help_text='Which email field this address appears in', max_length=10)),
                ('display_name', models.CharField(blank=True, help_text='Display name used in this specific message', max_length=255)),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_email_indexer.indexedemailaddress')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='google_email_indexer.googlemailmessage')),
            ],
        ),
        migrations.AddField(
            model_name='googlemailmessage',
            name='email_addresses',
            field=models.ManyToManyField(help_text='Email addresses that appear in this message', related_name='messages', through='google_email_indexer.MessageEmailAddress', to='google_email_indexer.indexedemailaddress'),
        ),
        migrations.AddIndex(
            model_name='messageemailaddress',
            index=models.Index(fields=['message', 'field'], name='google_emai_message_0a391f_idx'),
        ),
        migrations.AddIndex(
            model_name='messageemailaddress',
            index=models.Index(fields=['email_address', 'field'], name='google_emai_email_a_3a0a13_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageemailaddress',
            unique_together={('message', 'email_address', 'field')},
        ),
    ]
