# Generated by Django 5.2.3 on 2025-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_email_indexer', '0002_indexedemailaddress_messageemailaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexedemailaddress',
            name='first_seen',
            field=models.DateTimeField(help_text='When this email address first appeared in a message'),
        ),
        migrations.AlterField(
            model_name='indexedemailaddress',
            name='last_seen',
            field=models.DateTimeField(help_text='When this email address last appeared in a message'),
        ),
    ]
