# Generated by Django 5.2.3 on 2025-06-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_email_indexer', '0004_alter_indexedemailaddress_first_seen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesssageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inbox', models.EmailField(help_text='Inbox email address', max_length=254, verbose_name='Inbox')),
                ('labels', models.CharField(blank=True, help_text='Labels for the message source (comma separated list)', max_length=255, null=True, verbose_name='Labels')),
                ('description', models.TextField(blank=True, help_text='Description of the message source', null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the message source is active', verbose_name='Is Active')),
                ('priority', models.IntegerField(default=0, help_text='Priority of the message source', verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Message Source',
                'verbose_name_plural': 'Message Sources',
                'ordering': ['inbox'],
                'unique_together': {('inbox', 'labels')},
            },
        ),
    ]
