# Generated by Django 5.2.3 on 2025-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_email_indexer', '0005_messsagesource'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemailmessage',
            name='original_message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='googlemailmessage',
            index=models.Index(fields=['original_message_id'], name='google_emai_origina_242e23_idx'),
        ),
    ]
